import type { PetTemplate, SourceCandidate } from "./types";

export const PET_CLEANING_TEMPLATES: PetTemplate[] = [
  {
    id: "guest-smell-check",
    name: "Guest Smell Check",
    scenario: "cat_litter_odor",
    format: "POV + room reset + close-up proof",
    opening: "POV: someone is coming over and the litter box area still smells wrong.",
    structure: [
      "Open with social embarrassment in a real apartment scene.",
      "Show the exact odor source without overdramatizing.",
      "Introduce the product as a quick routine step.",
      "Show the after-state with a calmer room and owner reaction.",
      "End with a soft CTA around cleaner daily living.",
    ],
    bestFor: ["odor absorber", "deodorizing spray", "litter additive", "litter box filter"],
    riskNotes: ["Do not promise permanent odor removal.", "Avoid medical or disinfecting claims unless verified."],
  },
  {
    id: "cat-urine-accident",
    name: "Cat Urine Accident Fix",
    scenario: "cat_urine_cleanup",
    format: "incident hook + step-by-step cleanup + fabric result",
    opening: "If your cat has ever picked the rug instead of the litter box, you know this panic.",
    structure: [
      "Start with the incident and owner stress.",
      "Show blotting or surface prep as a believable first step.",
      "Apply the product with a clear close-up.",
      "Show texture, drying, and sniff-test style reaction.",
      "Close with a practical reminder to keep it ready.",
    ],
    bestFor: ["enzyme cleaner", "urine remover", "fabric odor spray"],
    riskNotes: ["Avoid saying it prevents future accidents.", "Avoid guaranteed stain removal on every fabric."],
  },
  {
    id: "litter-tracking-floor",
    name: "Litter Tracking Floor Test",
    scenario: "litter_tracking",
    format: "floor mess demo + mat interaction + cleanup comparison",
    opening: "This is what my floor looked like five minutes after cleaning.",
    structure: [
      "Show litter grains around the box from floor level.",
      "Capture the cat stepping out naturally.",
      "Show how the mat or tool catches litter.",
      "Lift, shake, or clean the product in one satisfying shot.",
      "Finish with a cleaner floor comparison.",
    ],
    bestFor: ["cat litter mat", "litter catcher", "floor cleaning tool"],
    riskNotes: ["Do not imply every litter type is fully captured.", "Avoid claims about all cats using it immediately."],
  },
  {
    id: "fur-on-black-clothes",
    name: "Fur On Black Clothes",
    scenario: "pet_hair_cleanup",
    format: "relatable outfit panic + tool pass + visible pickup",
    opening: "Black clothes and a shedding pet should come with a warning label.",
    structure: [
      "Show hair stuck on dark fabric, sofa, or bedding.",
      "Use the tool in a single clear pass.",
      "Show collected fur close-up as proof.",
      "Repeat on a second surface for credibility.",
      "End with ready-to-leave confidence.",
    ],
    bestFor: ["lint remover", "pet hair roller", "reusable fur brush", "vacuum attachment"],
    riskNotes: ["Avoid saying it works on every fabric.", "Do not invent durability or lifetime claims."],
  },
  {
    id: "sofa-smell-reset",
    name: "Sofa Smell Reset",
    scenario: "fabric_odor",
    format: "cozy home problem + fabric refresh routine + guest-ready result",
    opening: "The sofa looks clean, but pet homes have a smell test of their own.",
    structure: [
      "Open on a lived-in sofa or pet bed.",
      "Show the hidden odor problem with owner reaction.",
      "Apply the product as part of a weekly reset.",
      "Show fabric-safe handling and room atmosphere.",
      "Close with a guest-ready living room.",
    ],
    bestFor: ["fabric deodorizer", "pet bed spray", "odor absorber"],
    riskNotes: ["Avoid antimicrobial claims without proof.", "Avoid safety claims beyond provided product info."],
  },
  {
    id: "dog-pad-floor-reset",
    name: "Dog Pad Floor Reset",
    scenario: "dog_pad_floor",
    format: "daily mess + fast cleanup + habit loop",
    opening: "The puppy pad area is clean for about three minutes, then real life happens.",
    structure: [
      "Show the daily floor or pad-area mess.",
      "Introduce the product as a fast reset step.",
      "Show surface-level cleaning or odor control.",
      "Highlight repeat-use convenience.",
      "End with a calmer home routine.",
    ],
    bestFor: ["floor cleaner", "odor spray", "training pad accessory"],
    riskNotes: ["Avoid training outcome guarantees.", "Avoid pet health claims."],
  },
];

export const SOURCE_CATALOG: SourceCandidate[] = [
  {
    id: "odor-spray-enzymatic",
    title: "Pet enzyme odor remover spray for cat urine and fabric",
    productType: "enzyme odor spray",
    scenario: "cat_urine_cleanup",
    estimatedPriceCny: 12.8,
    suggestedRetailUsd: 19.99,
    monthlyOrderIndex: 86,
    supplierRating: 4.8,
    repeatPurchaseIndex: 82,
    visualDemoScore: 91,
    complianceRisk: "medium",
    keywords: ["cat urine", "enzyme", "odor remover", "fabric", "spray", "stain"],
    searchUrl: "https://s.1688.com/selloffer/offer_search.htm?keywords=pet%20enzyme%20odor%20remover%20spray",
    reasons: ["Strong before-after demo potential", "Useful for urgent cat accident scenarios", "Repeat purchase category"],
  },
  {
    id: "litter-deodorizer-beads",
    title: "Cat litter box deodorizer beads for daily odor control",
    productType: "litter deodorizer",
    scenario: "cat_litter_odor",
    estimatedPriceCny: 7.6,
    suggestedRetailUsd: 14.99,
    monthlyOrderIndex: 78,
    supplierRating: 4.7,
    repeatPurchaseIndex: 88,
    visualDemoScore: 76,
    complianceRisk: "low",
    keywords: ["cat litter", "deodorizer", "odor", "litter box", "beads", "fresh"],
    searchUrl: "https://s.1688.com/selloffer/offer_search.htm?keywords=cat%20litter%20box%20deodorizer",
    reasons: ["Clear cat-litter niche fit", "Low-cost consumable with repeat purchase potential", "Easy to bundle"],
  },
  {
    id: "double-layer-litter-mat",
    title: "Double-layer honeycomb cat litter mat",
    productType: "cat litter mat",
    scenario: "litter_tracking",
    estimatedPriceCny: 18.5,
    suggestedRetailUsd: 24.99,
    monthlyOrderIndex: 74,
    supplierRating: 4.6,
    repeatPurchaseIndex: 48,
    visualDemoScore: 95,
    complianceRisk: "low",
    keywords: ["cat litter mat", "tracking", "honeycomb", "floor", "cat litter", "mat"],
    searchUrl: "https://s.1688.com/selloffer/offer_search.htm?keywords=double%20layer%20cat%20litter%20mat",
    reasons: ["Very visible demo", "Strong problem-solution fit", "Low compliance risk"],
  },
  {
    id: "reusable-pet-hair-remover",
    title: "Reusable pet hair remover brush for sofa and clothes",
    productType: "pet hair remover",
    scenario: "pet_hair_cleanup",
    estimatedPriceCny: 9.9,
    suggestedRetailUsd: 16.99,
    monthlyOrderIndex: 82,
    supplierRating: 4.7,
    repeatPurchaseIndex: 44,
    visualDemoScore: 97,
    complianceRisk: "low",
    keywords: ["pet hair", "fur", "sofa", "clothes", "lint", "brush", "reusable"],
    searchUrl: "https://s.1688.com/selloffer/offer_search.htm?keywords=reusable%20pet%20hair%20remover",
    reasons: ["Instant visual proof", "Works across pet homes", "Easy creator-style demo"],
  },
  {
    id: "fabric-pet-odor-spray",
    title: "Pet-safe fabric odor control spray for sofa and pet bed",
    productType: "fabric odor spray",
    scenario: "fabric_odor",
    estimatedPriceCny: 10.5,
    suggestedRetailUsd: 18.99,
    monthlyOrderIndex: 69,
    supplierRating: 4.5,
    repeatPurchaseIndex: 79,
    visualDemoScore: 72,
    complianceRisk: "medium",
    keywords: ["fabric", "sofa", "pet bed", "odor spray", "deodorizer", "home"],
    searchUrl: "https://s.1688.com/selloffer/offer_search.htm?keywords=pet%20fabric%20odor%20spray",
    reasons: ["Good home-reset content angle", "Consumable SKU", "Useful for multi-pet households"],
  },
  {
    id: "dog-pad-deodorizer",
    title: "Dog pee pad area deodorizer and floor cleaning spray",
    productType: "dog floor deodorizer",
    scenario: "dog_pad_floor",
    estimatedPriceCny: 11.2,
    suggestedRetailUsd: 17.99,
    monthlyOrderIndex: 64,
    supplierRating: 4.4,
    repeatPurchaseIndex: 76,
    visualDemoScore: 74,
    complianceRisk: "medium",
    keywords: ["dog pad", "puppy", "floor", "odor", "cleaner", "spray"],
    searchUrl: "https://s.1688.com/selloffer/offer_search.htm?keywords=dog%20pad%20floor%20odor%20spray",
    reasons: ["Clear repeat-use routine", "Fits dog households", "Good daily reset angle"],
  },
];
