import type { PetTemplate, SourceCandidate } from "./types";

export const PET_CLEANING_TEMPLATES: PetTemplate[] = [
  {
    id: "guest-smell-check",
    name: "Guest Smell Check",
    scenario: "cat_litter_odor",
    format: "POV + room reset + close-up proof",
    opening: "POV: someone is coming over and the litter box area still smells wrong.",
    structure: [
      "Open with social embarrassment in a real apartment scene.",
      "Show the exact odor source without overdramatizing.",
      "Introduce the product as a quick routine step.",
      "Show the after-state with a calmer room and owner reaction.",
      "End with a soft CTA around cleaner daily living.",
    ],
    bestFor: ["odor absorber", "deodorizing spray", "litter additive", "litter box filter"],
    riskNotes: ["Do not promise permanent odor removal.", "Avoid medical or disinfecting claims unless verified."],
  },
  {
    id: "cat-urine-accident",
    name: "Cat Urine Accident Fix",
    scenario: "cat_urine_cleanup",
    format: "incident hook + step-by-step cleanup + fabric result",
    opening: "If your cat has ever picked the rug instead of the litter box, you know this panic.",
    structure: [
      "Start with the incident and owner stress.",
      "Show blotting or surface prep as a believable first step.",
      "Apply the product with a clear close-up.",
      "Show texture, drying, and sniff-test style reaction.",
      "Close with a practical reminder to keep it ready.",
    ],
    bestFor: ["enzyme cleaner", "urine remover", "fabric odor spray"],
    riskNotes: ["Avoid saying it prevents future accidents.", "Avoid guaranteed stain removal on every fabric."],
  },
  {
    id: "litter-tracking-floor",
    name: "Litter Tracking Floor Test",
    scenario: "litter_tracking",
    format: "floor mess demo + mat interaction + cleanup comparison",
    opening: "This is what my floor looked like five minutes after cleaning.",
    structure: [
      "Show litter grains around the box from floor level.",
      "Capture the cat stepping out naturally.",
      "Show how the mat or tool catches litter.",
      "Lift, shake, or clean the product in one satisfying shot.",
      "Finish with a cleaner floor comparison.",
    ],
    bestFor: ["cat litter mat", "litter catcher", "floor cleaning tool"],
    riskNotes: ["Do not imply every litter type is fully captured.", "Avoid claims about all cats using it immediately."],
  },
  {
    id: "fur-on-black-clothes",
    name: "Fur On Black Clothes",
    scenario: "pet_hair_cleanup",
    format: "relatable outfit panic + tool pass + visible pickup",
    opening: "Black clothes and a shedding pet should come with a warning label.",
    structure: [
      "Show hair stuck on dark fabric, sofa, or bedding.",
      "Use the tool in a single clear pass.",
      "Show collected fur close-up as proof.",
      "Repeat on a second surface for credibility.",
      "End with ready-to-leave confidence.",
    ],
    bestFor: ["lint remover", "pet hair roller", "reusable fur brush", "vacuum attachment"],
    riskNotes: ["Avoid saying it works on every fabric.", "Do not invent durability or lifetime claims."],
  },
  {
    id: "sofa-smell-reset",
    name: "Sofa Smell Reset",
    scenario: "fabric_odor",
    format: "cozy home problem + fabric refresh routine + guest-ready result",
    opening: "The sofa looks clean, but pet homes have a smell test of their own.",
    structure: [
      "Open on a lived-in sofa or pet bed.",
      "Show the hidden odor problem with owner reaction.",
      "Apply the product as part of a weekly reset.",
      "Show fabric-safe handling and room atmosphere.",
      "Close with a guest-ready living room.",
    ],
    bestFor: ["fabric deodorizer", "pet bed spray", "odor absorber"],
    riskNotes: ["Avoid antimicrobial claims without proof.", "Avoid safety claims beyond provided product info."],
  },
  {
    id: "dog-pad-floor-reset",
    name: "Dog Pad Floor Reset",
    scenario: "dog_pad_floor",
    format: "daily mess + fast cleanup + habit loop",
    opening: "The puppy pad area is clean for about three minutes, then real life happens.",
    structure: [
      "Show the daily floor or pad-area mess.",
      "Introduce the product as a fast reset step.",
      "Show surface-level cleaning or odor control.",
      "Highlight repeat-use convenience.",
      "End with a calmer home routine.",
    ],
    bestFor: ["floor cleaner", "odor spray", "training pad accessory"],
    riskNotes: ["Avoid training outcome guarantees.", "Avoid pet health claims."],
  },
  {
    id: "auto-litter-box-reveal",
    name: "Auto Litter Box Reveal",
    scenario: "auto_litter_box",
    format: "problem setup + unbox + daily routine proof",
    opening: "I used to scoop litter twice a day. Now I don't.",
    structure: [
      "Open with the daily scooping chore and owner frustration.",
      "Show the unboxing or setup in one clean shot.",
      "Demonstrate the auto-cleaning cycle with pet nearby.",
      "Highlight app or sensor features briefly.",
      "Close with freed-up time and cleaner home.",
    ],
    bestFor: ["automatic litter box", "self-cleaning litter box", "smart litter box"],
    riskNotes: ["Avoid health monitoring claims.", "Do not guarantee zero odor.", "Keep noise claims realistic."],
  },
  {
    id: "bath-time-hack",
    name: "Bath Time Hack",
    scenario: "pet_bathing",
    format: "struggle hook + product demo + calm result",
    opening: "Bath time used to be a war zone. Here's what changed.",
    structure: [
      "Show pet resisting or owner struggling at bath time.",
      "Introduce the product as a calming or easier solution.",
      "Demonstrate usage with clear water/product shots.",
      "Show the pet calm or the process smoother.",
      "End with a clean, happy pet and relieved owner.",
    ],
    bestFor: ["pet shampoo", "bath brush", "grooming glove", "drying towel"],
    riskNotes: ["Avoid skin treatment or medical claims.", "Do not claim calming effects without evidence."],
  },
  {
    id: "paw-cleanup-routine",
    name: "Paw Cleanup Routine",
    scenario: "paw_cleanup",
    format: "outdoor mess + quick clean + floor proof",
    opening: "Walk is done. Paws are a disaster. Here's the 30-second fix.",
    structure: [
      "Show muddy or dirty paws after a walk.",
      "Demonstrate the paw cleaner or wipe in action.",
      "Close-up of clean paws as proof.",
      "Show the clean floor as a result.",
      "End with a ready-for-couch moment.",
    ],
    bestFor: ["paw cleaner cup", "pet wipes", "paw washer", "muddy paw cleaner"],
    riskNotes: ["Avoid antibacterial claims unless verified.", "Do not claim to replace actual bathing."],
  },
  {
    id: "carpet-stain-rescue",
    name: "Carpet Stain Rescue",
    scenario: "pet_stain_removal",
    format: "stain panic + treatment + before-after",
    opening: "This stain has been here for three days. Watch what happens in 30 seconds.",
    structure: [
      "Show the stain with owner's visible concern.",
      "Apply the product with a clear demonstration.",
      "Show the lifting or cleaning action close-up.",
      "Reveal the clean result with a reaction.",
      "End with a practical tip or CTA.",
    ],
    bestFor: ["carpet cleaner", "stain remover", "enzyme cleaner", "upholstery cleaner"],
    riskNotes: ["Avoid guarantees on all fabric types.", "Do not claim permanent stain prevention."],
  },
  {
    id: "toy-sanitize-routine",
    name: "Toy Sanitize Routine",
    scenario: "pet_toys_cleaning",
    format: "germ awareness + easy clean + pet approval",
    opening: "Your pet's favorite toy is probably the dirtiest thing in your house.",
    structure: [
      "Show dirty, slimy, or smelly pet toys.",
      "Introduce the cleaning product or method.",
      "Demonstrate the cleaning process.",
      "Show the fresh toy returned to the pet.",
      "End with the pet happily playing.",
    ],
    bestFor: ["toy cleaner", "pet-safe sanitizer", "chew toy cleaner", "enzymatic soak"],
    riskNotes: ["Avoid germ-kill percentage claims.", "Ensure pet-safe claims are backed by product data."],
  },
  {
    id: "aquarium-maintenance",
    name: "Aquarium Maintenance Day",
    scenario: "aquarium_cleaning",
    format: "messy tank + tool demo + crystal clear result",
    opening: "The fish tank was starting to look like a swamp. Time for a reset.",
    structure: [
      "Show the cloudy or dirty aquarium.",
      "Introduce the cleaning tool or water treatment.",
      "Demonstrate the cleaning or treatment process.",
      "Show the clear water result with fish swimming.",
      "End with a maintenance tip.",
    ],
    bestFor: ["algae scraper", "water conditioner", "aquarium vacuum", "filter cleaner"],
    riskNotes: ["Avoid claims about fish health outcomes.", "Do not guarantee specific water parameters."],
  },
  {
    id: "dog-beach-cleanup",
    name: "Dog Beach Cleanup",
    scenario: "paw_cleanup",
    format: "outdoor adventure + sand/water mess + quick cleanup",
    opening: "Beach day was amazing. The car ride home is another story.",
    structure: [
      "Show the happy dog at the beach or park.",
      "Show the mess: sand, mud, wet fur in the car.",
      "Demonstrate the cleanup product in action.",
      "Show the clean dog and car interior.",
      "End with a next-adventure teaser.",
    ],
    bestFor: ["pet travel wipes", "car seat cover", "portable paw washer", "dog drying towel"],
    riskNotes: ["Do not imply waterproofing beyond product specs.", "Keep travel safety claims general."],
  },
  {
    id: "multi-cat-litter-upgrade",
    name: "Multi-Cat Litter Upgrade",
    scenario: "cat_litter_odor",
    format: "multi-cat chaos + solution + harmony",
    opening: "Three cats. One litter box. You do the math.",
    structure: [
      "Show the multi-cat household reality.",
      "Highlight the odor or tracking problem.",
      "Introduce the product as the upgrade.",
      "Show the improvement with cat reactions.",
      "End with a peaceful multi-cat home.",
    ],
    bestFor: ["large litter box", "odor-blocking litter", "litter deodorizer", "automatic litter box"],
    riskNotes: ["Avoid claims about reducing cat conflict.", "Do not guarantee odor elimination for all litter types."],
  },
];

export const SOURCE_CATALOG: SourceCandidate[] = [
  {
    id: "odor-spray-enzymatic",
    title: "Pet enzyme odor remover spray for cat urine and fabric",
    productType: "enzyme odor spray",
    scenario: "cat_urine_cleanup",
    estimatedPriceCny: 12.8,
    suggestedRetailUsd: 19.99,
    monthlyOrderIndex: 86,
    supplierRating: 4.8,
    repeatPurchaseIndex: 82,
    visualDemoScore: 91,
    complianceRisk: "medium",
    keywords: ["cat urine", "enzyme", "odor remover", "fabric", "spray", "stain"],
    searchUrl: "https://s.1688.com/selloffer/offer_search.htm?keywords=pet%20enzyme%20odor%20remover%20spray",
    reasons: ["Strong before-after demo potential", "Useful for urgent cat accident scenarios", "Repeat purchase category"],
  },
  {
    id: "litter-deodorizer-beads",
    title: "Cat litter box deodorizer beads for daily odor control",
    productType: "litter deodorizer",
    scenario: "cat_litter_odor",
    estimatedPriceCny: 7.6,
    suggestedRetailUsd: 14.99,
    monthlyOrderIndex: 78,
    supplierRating: 4.7,
    repeatPurchaseIndex: 88,
    visualDemoScore: 76,
    complianceRisk: "low",
    keywords: ["cat litter", "deodorizer", "odor", "litter box", "beads", "fresh"],
    searchUrl: "https://s.1688.com/selloffer/offer_search.htm?keywords=cat%20litter%20box%20deodorizer",
    reasons: ["Clear cat-litter niche fit", "Low-cost consumable with repeat purchase potential", "Easy to bundle"],
  },
  {
    id: "double-layer-litter-mat",
    title: "Double-layer honeycomb cat litter mat",
    productType: "cat litter mat",
    scenario: "litter_tracking",
    estimatedPriceCny: 18.5,
    suggestedRetailUsd: 24.99,
    monthlyOrderIndex: 74,
    supplierRating: 4.6,
    repeatPurchaseIndex: 48,
    visualDemoScore: 95,
    complianceRisk: "low",
    keywords: ["cat litter mat", "tracking", "honeycomb", "floor", "cat litter", "mat"],
    searchUrl: "https://s.1688.com/selloffer/offer_search.htm?keywords=double%20layer%20cat%20litter%20mat",
    reasons: ["Very visible demo", "Strong problem-solution fit", "Low compliance risk"],
  },
  {
    id: "reusable-pet-hair-remover",
    title: "Reusable pet hair remover brush for sofa and clothes",
    productType: "pet hair remover",
    scenario: "pet_hair_cleanup",
    estimatedPriceCny: 9.9,
    suggestedRetailUsd: 16.99,
    monthlyOrderIndex: 82,
    supplierRating: 4.7,
    repeatPurchaseIndex: 44,
    visualDemoScore: 97,
    complianceRisk: "low",
    keywords: ["pet hair", "fur", "sofa", "clothes", "lint", "brush", "reusable"],
    searchUrl: "https://s.1688.com/selloffer/offer_search.htm?keywords=reusable%20pet%20hair%20remover",
    reasons: ["Instant visual proof", "Works across pet homes", "Easy creator-style demo"],
  },
  {
    id: "fabric-pet-odor-spray",
    title: "Pet-safe fabric odor control spray for sofa and pet bed",
    productType: "fabric odor spray",
    scenario: "fabric_odor",
    estimatedPriceCny: 10.5,
    suggestedRetailUsd: 18.99,
    monthlyOrderIndex: 69,
    supplierRating: 4.5,
    repeatPurchaseIndex: 79,
    visualDemoScore: 72,
    complianceRisk: "medium",
    keywords: ["fabric", "sofa", "pet bed", "odor spray", "deodorizer", "home"],
    searchUrl: "https://s.1688.com/selloffer/offer_search.htm?keywords=pet%20fabric%20odor%20spray",
    reasons: ["Good home-reset content angle", "Consumable SKU", "Useful for multi-pet households"],
  },
  {
    id: "dog-pad-deodorizer",
    title: "Dog pee pad area deodorizer and floor cleaning spray",
    productType: "dog floor deodorizer",
    scenario: "dog_pad_floor",
    estimatedPriceCny: 11.2,
    suggestedRetailUsd: 17.99,
    monthlyOrderIndex: 64,
    supplierRating: 4.4,
    repeatPurchaseIndex: 76,
    visualDemoScore: 74,
    complianceRisk: "medium",
    keywords: ["dog pad", "puppy", "floor", "odor", "cleaner", "spray"],
    searchUrl: "https://s.1688.com/selloffer/offer_search.htm?keywords=dog%20pad%20floor%20odor%20spray",
    reasons: ["Clear repeat-use routine", "Fits dog households", "Good daily reset angle"],
  },
  {
    id: "automatic-litter-box",
    title: "Self-cleaning automatic litter box with app control",
    productType: "automatic litter box",
    scenario: "auto_litter_box",
    estimatedPriceCny: 289,
    suggestedRetailUsd: 399.99,
    monthlyOrderIndex: 92,
    supplierRating: 4.6,
    repeatPurchaseIndex: 35,
    visualDemoScore: 94,
    complianceRisk: "medium",
    keywords: ["automatic litter box", "self-cleaning", "smart", "cat", "app control"],
    searchUrl: "https://s.1688.com/selloffer/offer_search.htm?keywords=automatic%20self%20cleaning%20litter%20box",
    reasons: ["High-ticket item with strong demo potential", "Growing market demand", "Clear before-after transformation"],
  },
  {
    id: "pet-bath-brush",
    title: "Silicone pet bathing brush with shampoo dispenser",
    productType: "bath brush",
    scenario: "pet_bathing",
    estimatedPriceCny: 8.5,
    suggestedRetailUsd: 14.99,
    monthlyOrderIndex: 71,
    supplierRating: 4.5,
    repeatPurchaseIndex: 42,
    visualDemoScore: 88,
    complianceRisk: "low",
    keywords: ["pet bath", "brush", "shampoo", "grooming", "silicone", "dog", "cat"],
    searchUrl: "https://s.1688.com/selloffer/offer_search.htm?keywords=silicone%20pet%20bath%20brush%20shampoo",
    reasons: ["Low-cost impulse buy", "Easy demo with lather shots", "Universal pet owner need"],
  },
  {
    id: "paw-cleaner-cup",
    title: "Portable paw cleaner cup with soft silicone bristles",
    productType: "paw cleaner",
    scenario: "paw_cleanup",
    estimatedPriceCny: 12.5,
    suggestedRetailUsd: 19.99,
    monthlyOrderIndex: 79,
    supplierRating: 4.7,
    repeatPurchaseIndex: 38,
    visualDemoScore: 96,
    complianceRisk: "low",
    keywords: ["paw cleaner", "dog", "muddy", "portable", "silicone", "washer"],
    searchUrl: "https://s.1688.com/selloffer/offer_search.htm?keywords=portable%20paw%20cleaner%20cup%20silicone",
    reasons: ["Viral-friendly demo", "Strong problem-solution fit", "Seasonal demand spikes"],
  },
  {
    id: "carpet-enzyme-cleaner",
    title: "Enzyme-based carpet stain remover for pet messes",
    productType: "carpet cleaner",
    scenario: "pet_stain_removal",
    estimatedPriceCny: 15.8,
    suggestedRetailUsd: 22.99,
    monthlyOrderIndex: 77,
    supplierRating: 4.6,
    repeatPurchaseIndex: 85,
    visualDemoScore: 89,
    complianceRisk: "medium",
    keywords: ["carpet cleaner", "stain remover", "enzyme", "pet", "urine", "odor"],
    searchUrl: "https://s.1688.com/selloffer/offer_search.htm?keywords=enzyme%20carpet%20stain%20remover%20pet",
    reasons: ["High repeat purchase rate", "Satisfying before-after demo", "Essential for pet households"],
  },
  {
    id: "pet-toy-sanitizer",
    title: "Pet-safe toy cleaning spray and sanitizer",
    productType: "toy cleaner",
    scenario: "pet_toys_cleaning",
    estimatedPriceCny: 9.2,
    suggestedRetailUsd: 15.99,
    monthlyOrderIndex: 58,
    supplierRating: 4.3,
    repeatPurchaseIndex: 72,
    visualDemoScore: 71,
    complianceRisk: "medium",
    keywords: ["pet toy", "cleaner", "sanitizer", "safe", "spray", "hygiene"],
    searchUrl: "https://s.1688.com/selloffer/offer_search.htm?keywords=pet%20toy%20sanitizer%20cleaner%20spray",
    reasons: ["Emerging hygiene awareness niche", "Bundle opportunity with toys", "Educational content angle"],
  },
  {
    id: "algae-scraper-aquarium",
    title: "Magnetic aquarium algae scraper cleaner",
    productType: "algae scraper",
    scenario: "aquarium_cleaning",
    estimatedPriceCny: 18.9,
    suggestedRetailUsd: 24.99,
    monthlyOrderIndex: 62,
    supplierRating: 4.5,
    repeatPurchaseIndex: 31,
    visualDemoScore: 82,
    complianceRisk: "low",
    keywords: ["aquarium", "algae", "scraper", "fish tank", "cleaner", "magnetic"],
    searchUrl: "https://s.1688.com/selloffer/offer_search.htm?keywords=magnetic%20aquarium%20algae%20scraper",
    reasons: ["Clear visual transformation", "Niche but dedicated audience", "Low compliance risk"],
  },
  {
    id: "dog-drying-towel",
    title: "Super absorbent microfiber dog drying towel",
    productType: "drying towel",
    scenario: "pet_bathing",
    estimatedPriceCny: 6.8,
    suggestedRetailUsd: 12.99,
    monthlyOrderIndex: 68,
    supplierRating: 4.4,
    repeatPurchaseIndex: 33,
    visualDemoScore: 84,
    complianceRisk: "low",
    keywords: ["dog towel", "drying", "microfiber", "absorbent", "pet", "bath"],
    searchUrl: "https://s.1688.com/selloffer/offer_search.htm?keywords=microfiber%20dog%20drying%20towel",
    reasons: ["Low price point", "Easy upsell with grooming products", "Seasonal bath-time demand"],
  },
  {
    id: "pet-hair-vacuum-attachment",
    title: "Pet hair removal vacuum attachment for furniture",
    productType: "vacuum attachment",
    scenario: "pet_hair_cleanup",
    estimatedPriceCny: 22.5,
    suggestedRetailUsd: 29.99,
    monthlyOrderIndex: 73,
    supplierRating: 4.6,
    repeatPurchaseIndex: 28,
    visualDemoScore: 91,
    complianceRisk: "low",
    keywords: ["pet hair", "vacuum", "attachment", "furniture", "sofa", "fur remover"],
    searchUrl: "https://s.1688.com/selloffer/offer_search.htm?keywords=pet%20hair%20vacuum%20attachment%20furniture",
    reasons: ["Satisfying suction demo", "Fits existing vacuum owners", "Cross-sell opportunity"],
  },
  {
    id: "pet-safe-floor-cleaner",
    title: "Pet-safe floor cleaning solution for all surfaces",
    productType: "floor cleaner",
    scenario: "dog_pad_floor",
    estimatedPriceCny: 13.5,
    suggestedRetailUsd: 18.99,
    monthlyOrderIndex: 66,
    supplierRating: 4.5,
    repeatPurchaseIndex: 81,
    visualDemoScore: 68,
    complianceRisk: "low",
    keywords: ["pet safe", "floor cleaner", "non-toxic", "all surfaces", "dog", "cat"],
    searchUrl: "https://s.1688.com/selloffer/offer_search.htm?keywords=pet%20safe%20floor%20cleaner%20non%20toxic",
    reasons: ["High repeat purchase", "Pet safety positioning", "Works for all pet households"],
  },
];
